# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from .extended_keyword_create_params import ExtendedKeywordCreateParams as ExtendedKeywordCreateParams
from .keywords_by_list_create_params import KeywordsByListCreateParams as KeywordsByListCreateParams
from .keywords_by_page_create_params import KeywordsByPageCreateParams as KeywordsByPageCreateParams
from .dictionary_by_page_create_params import DictionaryByPageCreateParams as DictionaryByPageCreateParams
from .extended_keyword_create_response import ExtendedKeywordCreateResponse as ExtendedKeywordCreateResponse
from .keywords_by_list_create_response import KeywordsByListCreateResponse as KeywordsByListCreateResponse
from .keywords_by_page_create_response import KeywordsByPageCreateResponse as KeywordsByPageCreateResponse
from .dictionary_by_page_create_response import DictionaryByPageCreateResponse as DictionaryByPageCreateResponse
from .concurents_by_keyword_create_params import ConcurentsByKeywordCreateParams as ConcurentsByKeywordCreateParams
from .dictionary_ext_by_page_create_params import DictionaryExtByPageCreateParams as DictionaryExtByPageCreateParams
from .concurents_by_keyword_create_response import (
    ConcurentsByKeywordCreateResponse as ConcurentsByKeywordCreateResponse,
)
from .dictionary_ext_by_page_create_response import (
    DictionaryExtByPageCreateResponse as DictionaryExtByPageCreateResponse,
)
